#!/bin/bash

PLAYLISTNAME=""

usage() {                                      
  echo "Usage: $0 [ -n PLAYLISTNAME ]  [ -s SONG ] [ -a ALL ]" 1>&2 
}
exit_abnormal() {                              # Function: Exit with error.
  usage
  exit 1
}
while getopts ":n:" options; do
  case "${options}" in                         
    n)                                         
      PLAYLISTNAME=${OPTARG}                    
      ;;
	
    :)                                         # If expected argument omitted:
      echo "Error: -${OPTARG} requires an argument."
      exit_abnormal                            # Exit abnormally.
      ;;
    *)                                         # If unknown (any other) option:
      exit_abnormal                            # Exit abnormally.
      ;;
  esac
done

shuf "${PLAYLISTNAME}" -o "${PLAYLISTNAME}"
